web:
    image: php:7.1-apache
    links:
     - mysql
    environment:
     - STAGING=true
    ports:
     - "8080:80"
    working_dir: /var/www/html
    volumes:
     - .:/var/www/html/
mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
